### ISSUE TITLE
O- and N- searches 

### ISSUE THREAD

**Issue by ValentinaRangelAngarita** [pFindStudio/pGlyco3#4]
Hi! 
Is there any way I can do a search for N- and O- glycan simulatenously? (I am looking at a raw file that has both N- and O-). Should I just create a new database with both N- and O- and run it in either mode? or would the 138/144 ratio affect the search?
Thank you!

**Comment by jalew188** [comment]
We are working on this. By using pGlycoSite with combined N- and O- GDB, we can always obtain localized glycans at N- and O-sites, but the problem is the accuracy validation.

We do not check 138/144 intensity ratio or other oxonium ion ratios to classify N/O-glycans when identification and localization, so it is not a problem. 

Creating N+O GDB is a bit tricky, but I can share the GDB onto github if you want. Searching for N+O-glycans is not straightforward as well, you can only use command line with some special parameters.

**Comment by jalew188** [comment]
Hi @ValentinaRangelAngarita , another problem for combined N- and O-GDB is that, pGlycoSite will check the localized glycan if the glycan is in the glycan GDB. N-glycan should be checked by N-GDB, and O-glycan should be checked by O-GDB. pGlycoSite cannot do the checking separately currently if combined GDB is used.
